// const geistSans = localFont({
//   src: "../../../fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "../../../fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

import { Outlet } from "react-router-dom";
import Header from "./component/header";
import Sidebar from "./component/sidebar";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function DashboardLayout() {
  // const locale = await getLocale();
  // console.log(locale);

  return (
    <div
      className="grid min-h-screen h-full w-full md:grid-cols-[220px_1fr] lg:grid-cols-[280px_1fr] antialiased font-[family-name:var(--font-geist-sans)]"
      // className={`${geistSans.variable} ${geistMono.variable} grid min-h-screen h-full w-full md:grid-cols-[220px_1fr] lg:grid-cols-[280px_1fr] antialiased font-[family-name:var(--font-geist-sans)]`}
    >
      <Sidebar />
      <div className="flex flex-col">
        <Header />
        <main className="flex flex-1 flex-col gap-4 p-4 lg:gap-6 lg:p-6">
          <Outlet />
        </main>
      </div>
    </div>
  );
}
